package amazons;

import ucb.gui2.TopLevel;
import ucb.gui2.LayoutSpec;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import java.util.concurrent.ArrayBlockingQueue;

/** The GUI controller for an Amazons board and buttons.
 *  @author Bryan Ho
 */
class GUI extends TopLevel implements View, Reporter {

    /** Minimum size of board in pixels. */
    private static final int MIN_SIZE = 500;

    /** A new window with given TITLE providing a view of an Amazons board. */
    GUI(String title) {
        super(title, true);
        addMenuButton("Game->New", this::newGame);
        addMenuButton("Game->Quit", this::quit);
        addMenuButton("Settings->Seed", this::newSeed);
        addMenuButton("Settings->Auto", this::autoHelper);
        addMenuButton("Settings->Manual", this::manualHelper);

        _widget = new BoardWidget(_pendingCommands);
        add(_widget,
            new LayoutSpec("y", 1,
                           "height", 1,
                           "width", 3));
    }

    /** Response to "Quit" button click. */
    private void quit(String dummy) {
        _pendingCommands.offer("quit");
    }

    /** Pattern describing the 'seed' command's arguments. */
    private static final Pattern SEED_PATN =
        Pattern.compile("\\s*(-?\\d{1,18})\\s*$");

    /** Response to "Seed" button click. */
    private void newSeed(String dummy) {
        String response =
            getTextInput("Enter new random seed.",
                         "New seed",  "plain", "");
        if (response != null) {
            Matcher mat = SEED_PATN.matcher(response);
            if (mat.matches()) {
                _pendingCommands.offer(String.format("seed %s", mat.group(1)));
            } else {
                showMessage("Enter an integral seed value.", "Error", "error");
            }
        }
    }

    /** Creates new game. */
    private void newGame(String dummy) {
        _pendingCommands.offer("new");
    }

    /** Replaces player with AI. */
    private void autoHelper(String dummy) {
        String response =
                getTextInput("Which player should be set to auto?",
                        "Player set auto", "plain", "");
        if (response != null) {
            if (response.toUpperCase().equals("WHITE")) {
                _pendingCommands.offer(String.format("auto white"));
            } else if (response.toUpperCase().equals("BLACK")) {
                _pendingCommands.offer(String.format("auto black"));
            } else {
                showMessage("Enter a valid player", "Error", "error");
            }
        } else {
            showMessage("Enter a valid player", "Error", "error");
        }
    }

    /** Replaces player with manual player. */
    private void manualHelper(String dummy) {
        String response =
                getTextInput("Which player should be set to manual?",
                        "Player set manual", "plain", "");
        if (response != null) {
            if (response.toUpperCase().equals("WHITE")) {
                _pendingCommands.offer(String.format("manual white"));
            } else if (response.toUpperCase().equals("BLACK")) {
                _pendingCommands.offer(String.format("manual black"));
            } else {
                showMessage("Enter a valid player", "Error", "error");
            }
        } else {
            showMessage("Enter a valid player", "Error", "error");
        }
    }


    /** Return the next command from our widget, waiting for it as necessary.
     *  The BoardWidget uses _pendingCommands to queue up moves that it
     *  receives.  This class uses _pendingCommands to queue up commands that
     *  are generated by clicking on menu items. */
    String readCommand() {
        try {
            _widget.setMoveCollection(true);
            if (_widget.guiCommands().size() > 0) {
                _pendingCommands.put(_widget.guiCommands().take());
            }
            String cmnd = _pendingCommands.take();
            _widget.setMoveCollection(false);
            return cmnd;
        } catch (InterruptedException excp) {
            throw new Error("unexpected interrupt");
        }
    }

    @Override
    public void update(Board board) {
        _widget.update(board);
    }

    @Override
    public void reportError(String fmt, Object... args) {
        showMessage(String.format(fmt, args), "Amazons Error", "error");
    }

    @Override
    public void reportNote(String fmt, Object... args) {
        showMessage(String.format(fmt, args), "Amazons Message", "information");
    }

    @Override
    public void reportMove(Move unused) {
    }

    /** The board widget. */
    private BoardWidget _widget;

    /** Queue of pending commands resulting from menu clicks and moves on the
     *  board.  We use a blocking queue because the responses to clicks
     *  on the board and on menus happen in parallel to the methods that
     *  call readCommand, which therefore needs to wait for clicks to happen. */
    private ArrayBlockingQueue<String> _pendingCommands =
        new ArrayBlockingQueue<>(5);

}
